services:
  plc_sniffer:
    build:
      context: .
      dockerfile: Dockerfile.secure
    image: ghcr.io/oriolrius/plc_sniffer:latest
    # Required for packet capture
    privileged: true
    network_mode: host
    environment:
      - LOG_LEVEL=INFO
      - INTERFACE=br-lan
      - FILTER=udp port 40000
      - DESTINATION_IP=10.121.102.1
      - DESTINATION_PORT=40000
      - RATE_LIMIT=0
      - HEALTH_CHECK_PORT=8080
      - RUN_AS_ROOT=true