services:
  plc_sniffer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ymbihq/plc_sniffer
    privileged: true
    network_mode: host
    environment:
      - LOGLEVEL=INFO
      - IFACE=br-lan
      - FILTER=(udp port 40000)
      - UDP_IP=10.121.101.1
      - UDP_PORT=40000
