version: '3.8'

services:
  plc_sniffer:
    build:
      context: .
      dockerfile: Dockerfile.secure
    image: plc-sniffer:secure
    container_name: plc_sniffer_secure
    restart: unless-stopped
    
    # Use capabilities instead of privileged mode
    cap_add:
      - NET_RAW
      - NET_ADMIN
    
    # Run as non-root user
    user: "1000:1000"
    
    network_mode: host
    
    environment:
      - INTERFACE=eth0
      - FILTER=udp
      - DESTINATION_IP=127.0.0.1
      - DESTINATION_PORT=8514
      - LOG_LEVEL=INFO
      - MAX_PACKET_SIZE=65535
      - RATE_LIMIT=10000  # 10k pps limit
      
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os._exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"