services:
  plc_sniffer:
    build:
      context: .
      dockerfile: Dockerfile.secure
    image: ghcr.io/oriolrius/plc_sniffer:latest
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: host
    environment:
      - LOG_LEVEL=INFO
      - INTERFACE=eth0
      - FILTER=udp port 40000
      - DESTINATION_IP=10.121.101.1
      - DESTINATION_PORT=40000
      - RATE_LIMIT=0
